feat: LEAP-572: Implement interface indicator for expired plans
HumanSignal/dm2 pull request #308
Opened 2024-02-27 15:01 UTC by juliosgarbi

### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2024-02-27 15:38 UTC, yyassi-heartex commented on src/components/Common/SDKButtons.js
> +    />
```suggestion
    />
```

2024-02-27 15:40 UTC, yyassi-heartex approved these changes
approved, just one minor replacement

2024-02-28 12:57 UTC, hlomzik commented on src/components/DataManager/Toolbar/instruments.js
> +import { Block } from "../../../utils/bem";
please move them up to fit the order

2024-02-28 13:49 UTC, juliosgarbi commented on src/components/DataManager/Toolbar/instruments.js
> +import { Block } from "../../../utils/bem";
Alphabetical order?

2024-02-29 13:30 UTC, hlomzik requested changes

2024-02-29 13:30 UTC, hlomzik commented on src/components/DataManager/Toolbar/instruments.js
> +const isSelfServeExpiredSubscription = isSelfServe && window.APP_SETTINGS.subscription.current_period_end && new Date(window.APP_SETTINGS.subscription.current_period_end) < new Date();
move these long items to consts as well as in LSP

2024-02-29 15:16 UTC, merged